// Build-time codegen: read content/journal/*.mdx and emit lib/journal.data.ts
// so the journal never touches node:fs at runtime (Cloudflare Workers has no
// filesystem). Run automatically before builds; the output is committed.
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const ROOT = process.cwd();
const JOURNAL_DIR = path.join(ROOT, "content", "journal");
const OUT = path.join(ROOT, "lib", "journal.data.ts");

const essays = fs
  .readdirSync(JOURNAL_DIR)
  .filter((f) => f.endsWith(".mdx"))
  .map((f) => {
    const slug = f.replace(/\.mdx$/, "");
    const raw = fs.readFileSync(path.join(JOURNAL_DIR, f), "utf8");
    const { data, content } = matter(raw);
    return {
      slug,
      title: String(data.title ?? slug),
      date: String(data.date ?? ""),
      order: Number(data.order ?? 0),
      author: String(data.author ?? "Neosmart"),
      dek: String(data.dek ?? ""),
      description: String(data.description ?? data.dek ?? ""),
      ogTitle: String(data.ogTitle ?? data.title ?? slug),
      body: content,
    };
  })
  .sort((a, b) => a.order - b.order);

const banner =
  "// AUTO-GENERATED by scripts/gen-journal.mjs — do not edit by hand.\n" +
  "// Regenerate with: npm run gen:journal\n";

const file =
  banner +
  'import type { Essay } from "./journal";\n\n' +
  "export const ESSAYS: Essay[] = " +
  JSON.stringify(essays, null, 2) +
  ";\n";

fs.writeFileSync(OUT, file);
console.log(`gen-journal: wrote ${essays.length} essays -> ${path.relative(ROOT, OUT)}`);
